In [11]:
# # # # 获取数据集Energy均值和标准差
import lmdb
import pickle
import numpy as np

lmdb_p = '/media/liud/Liud_FX2T/dataset/OC20/is2re_100k/select_data/all_stru/100k/vector/train'
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
# # # # 获取数据集均值和标准差
import torch
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    y_list = []
    for key, value in cursor:
        info = pickle.loads(value)
        y_list.append(info.y)
    y_list = torch.tensor(y_list)
    target_mean = torch.mean(y_list, dim=0)
    target_std = torch.std(y_list, dim=0)
    print(target_mean)
    # print(target_mean, target_std)
    print(target_std)

tensor(-1.3742, dtype=torch.float64)
tensor(2.0359, dtype=torch.float64)


In [46]:
# # # # 获取数据集Vetor均值和标准差
import lmdb
import pickle
import numpy as np

lmdb_p = '/media/liud/Liud_FX2T/dataset/OC20/is2re_10k/select_data/tag1&2/vector/train'
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
import torch
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    y_list = []
    for key, value in cursor:
        info = pickle.loads(value)
        # tags = info.tags
        # tags12 = torch.where(tags > 0)[0]
        # src, dst = info.edge_index
        # cond1 = torch.isin(src, tags12)
        # cond2 = torch.isin(dst, tags12)
        # # 结合所有条件，生成一个布尔掩码
        # mask = cond1 | cond2
        # v = info.v1[mask]
        v = info.v1
        y_list.extend(v.tolist())
    y_list = torch.tensor(y_list)
    target_mean = torch.mean(y_list, dim=0)
    target_std = torch.std(y_list, dim=0)
    print(target_mean)
    # print(target_mean, target_std)
    print(target_std)

tensor([6.1891e-10, 3.0946e-10, 1.6440e-10])
tensor([3.6006, 3.5680, 2.0241])


In [49]:
# 查看lmdb中的数据
import lmdb
import pickle
import numpy as np

lmdb_p = "/home/liud/Documents/code/ocp/results"
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
# 遍历所有键值对，并只打印前 5 个数据
print("First 5 entries in the database:")
count = 0
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    for key, value in cursor:
        if value is not None:
            try:
                data = pickle.loads(value)
                print(f"Key: {key.decode()}")
                print("Data:", data)
                # print("atomic_numbers:", type(data.atomic_numbers))
                # print("y", type(data.y))
                # print('sid', type(data.sid))
                print("tags:", data.tags)
                print("tags:", data.v0)
                print("tags:", data.v1)
                print(data.edge_index[1][0:300])
                # print("pos:", type(data.pos))
                # print(("distances:", len(data.distances)))
                # print("edge_index:", type(data.edge_index))
                # print("distances:", type(data.distances))
                # print("features:", type(data.features))
            except Exception as e:
                print(f"Error processing key {key}: {e}")
        else:
            print(f"No data found for key: {key.decode()}")
        count += 1
        if count >= 3:
            break



First 5 entries in the database:
Key: 0
Data: DataBatch(edge_index=[2, 2006], y=[1], pos=[68, 3], y_init=[1], y_relaxed=[1], pos_relaxed=[68, 3], force=[68, 3], atomic_numbers=[68], natoms=[1], tags=[68], fixed=[68], distances=[1362], cell_offsets=[2006, 3], cell=[1, 3, 3], sid=[1], ads_id=[1], batch=[68], ptr=[2], v1=[2006, 3], v1_num=2006, neighbors=[1], id_swap=[2006], v0=[2006, 3])
tags: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       dtype=torch.int16)
tags: tensor([[ 1.5802, -4.3612, -4.4834],
        [-3.1605, -0.0000, -4.8356],
        [ 0.7915, -2.8884, -1.6651],
        ...,
        [-5.0370, -0.2430, -5.9637],
        [ 6.7991,  1.2298, -1.6566],
        [-2.6823,  1.2298, -2.3610]])
tags: tensor([[-1.5800,  4.3600,  4.4800],
        [ 3.1600, -0.0000,  4.8400],
        [-0.7900,  2.8900,  

In [12]:
# 计算lmdb文件中的数据条目数
import lmdb

def count_entries_in_lmdb(lmdb_path):
    env = lmdb.open(lmdb_path, readonly=True, lock=False)
    with env.begin() as txn:
        cursor = txn.cursor()
        count = sum(1 for _ in cursor)
    return count

if __name__ == "__main__":
    lmdb_path = "/media/liud/Liud_FX2T/dataset/OC20/is2re_10k/select_data/tag1&2/test"  # 替换为你的LMDB文件路径
    num_entries = count_entries_in_lmdb(lmdb_path)
    print(f"Number of entries in the LMDB file: {num_entries}")


Number of entries in the LMDB file: 1116


In [16]:
# 读取pt文件
import torch
data = torch.load("/home/liud/Documents/code/ocp/configs/s2ef/all/gemnet/scaling_factors/gemnet-oc_1.pt")
print(data)

{'int_blocks.0.trip_interaction.scale_rbf': Parameter containing:
tensor(8.6465), 'int_blocks.0.trip_interaction.scale_cbf_sum': Parameter containing:
tensor(4.6171), 'int_blocks.0.quad_interaction.scale_rbf': Parameter containing:
tensor(9.0613), 'int_blocks.0.quad_interaction.scale_cbf': Parameter containing:
tensor(30.9794), 'int_blocks.0.quad_interaction.scale_sbf_sum': Parameter containing:
tensor(8.7431), 'int_blocks.0.atom_edge_interaction.scale_rbf': Parameter containing:
tensor(8.6083), 'int_blocks.0.atom_edge_interaction.scale_cbf_sum': Parameter containing:
tensor(5.6123), 'int_blocks.0.edge_atom_interaction.scale_rbf': Parameter containing:
tensor(9.0417), 'int_blocks.0.edge_atom_interaction.scale_cbf_sum': Parameter containing:
tensor(0.5292), 'int_blocks.0.atom_interaction.scale_rbf_sum': Parameter containing:
tensor(0.5019), 'int_blocks.0.atom_update.scale_sum': Parameter containing:
tensor(0.7639), 'int_blocks.1.trip_interaction.scale_rbf': Parameter containing:
tensor(

tensor([10,  2, 20,  4, 30])
