In [1]:
# # # # 获取数据集Energy均值和标准差
import lmdb
import pickle
import numpy as np

lmdb_p = '/media/liud/lnz_2t/OC22/is2res_total_train_val_test_lmdbs/data/oc22/is2re/train'
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
# # # # 获取数据集均值和标准差
import torch
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    y_list = []
    for key, value in cursor:
        info = pickle.loads(value)
        y_list.append(info.y)
    y_list = torch.tensor(y_list)
    target_mean = torch.mean(y_list, dim=0)
    target_std = torch.std(y_list, dim=0)
    print(target_mean)
    # print(target_mean, target_std)
    print(target_std)

tensor(-523.8716, dtype=torch.float64)
tensor(228.1776, dtype=torch.float64)


In [13]:
# # # # 获取数据集Vetor均值和标准差
import lmdb
import pickle
import numpy as np

lmdb_p = '/media/liud/lnz_2t/OC20/is2re/100k/tags12/50k/test'
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
import torch
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    y_list = []
    d_max = []
    for key, value in cursor:
        info = pickle.loads(value)
        pos1 = info.pos
        pos2 = info.pos_relaxed
        dist = torch.norm(pos2-pos1, dim=1).unsqueeze(0)
        d_max.append(torch.max(dist))
        dist = dist.tolist()
        y_list.extend(dist[0])
        # tags = info.tags
        # tags12 = torch.where(tags > 0)[0]
        # src, dst = info.edge_index
        # cond1 = torch.isin(src, tags12)
        # cond2 = torch.isin(dst, tags12)
        # # 结合所有条件，生成一个布尔掩码
        # mask = cond1 | cond2
        # v = info.v1[mask]
        # v = info.v1
        # y_list.extend(v.tolist())
    print(m)
    print(len(d_max))
    print(len(y_list))
    # y_list = torch.tensor(y_list)
    # target_mean = torch.mean(y_list, dim=0)
    # target_std = torch.std(y_list, dim=0)
    # print(target_mean)
    # # print(target_mean, target_std)
    # print(target_std)

10000
251679


In [1]:
# 查看lmdb中的数据
import lmdb
import pickle
import numpy as np
from ase.visualize import view

lmdb_p = "/media/liud/lnz_2t/Cu_single/combined/0/tags/train"
env = lmdb.open(lmdb_p, map_size=1099511627776, readonly=True, lock=False)
# 遍历所有键值对，并只打印前 5 个数据
print("First 5 entries in the database:")
count = 0
with env.begin(write=False) as txn:
    cursor = txn.cursor()
    for key, value in cursor:
        if value is not None:
            try:
                data = pickle.loads(value)
                print(f"Key: {key.decode()}")
                print("Data:", data)
                print(data.sid)
                print(data.tags)
                print(data.fixed)
                # print(data.ptr)
                # print("atomic_numbers:", type(data.atomic_numbers))
                # print("y", type(data.y))
                # print('sid', type(data.sid))
                # print("tags:", data.tags)
                # print("tags:", data.v0)
                # print("tags:", data.v1)
                # print(data.edge_index[1][0:300])
                # print("pos:", type(data.pos))
                # print(("distances:", len(data.distances)))
                # print("edge_index:", type(data.edge_index))
                # print("distances:", type(data.distances))
                # print("features:", type(data.features))
            except Exception as e:
                print(f"Error processing key {key}: {e}")
        else:
            print(f"No data found for key: {key.decode()}")
        count += 1
        if count >= 10:
            break



First 5 entries in the database:
Key: 0
Data: Data(pos=[20, 3], cell=[1, 3, 3], atomic_numbers=[20], natoms=20, y=1.9326293499999991, tags=[20], edge_index=[2, 570], cell_offsets=[570, 3], distances=[570], force=[20, 3], fixed=[20], y_relaxed=-0.536564, sfid=0, sid=2401, pos_relaxed=[20, 3], force_relaxed=[38, 3], distances_relaxed=[570])
2401
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Key: 1
Data: Data(pos=[26, 3], cell=[1, 3, 3], atomic_numbers=[26], natoms=26, y=0.0385585300000173, tags=[26], edge_index=[2, 614], cell_offsets=[614, 3], distances=[614], force=[26, 3], fixed=[26], y_relaxed=-1.546374, sfid=3, sid=779, pos_relaxed=[26, 3], force_relaxed=[42, 3], distances_relaxed=[614])
779
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [5]:
# 计算lmdb文件中的数据条目数
import lmdb

def count_entries_in_lmdb(lmdb_path):
    env = lmdb.open(lmdb_path, readonly=True, lock=False)
    with env.begin() as txn:
        cursor = txn.cursor()
        count = sum(1 for _ in cursor)
    return count

if __name__ == "__main__":
    lmdb_path = "/media/liud/lnz_2t/Cu_single/combined/0/train"  # 替换为你的LMDB文件路径
    num_entries = count_entries_in_lmdb(lmdb_path)
    print(f"Number of entries in the LMDB file: {num_entries}")


Number of entries in the LMDB file: 1845


In [16]:
# 读取pt文件
import torch
data = torch.load("/home/liud/Documents/code/ocp/configs/s2ef/all/gemnet/scaling_factors/gemnet-oc_1.pt")
print(data)

{'int_blocks.0.trip_interaction.scale_rbf': Parameter containing:
tensor(8.6465), 'int_blocks.0.trip_interaction.scale_cbf_sum': Parameter containing:
tensor(4.6171), 'int_blocks.0.quad_interaction.scale_rbf': Parameter containing:
tensor(9.0613), 'int_blocks.0.quad_interaction.scale_cbf': Parameter containing:
tensor(30.9794), 'int_blocks.0.quad_interaction.scale_sbf_sum': Parameter containing:
tensor(8.7431), 'int_blocks.0.atom_edge_interaction.scale_rbf': Parameter containing:
tensor(8.6083), 'int_blocks.0.atom_edge_interaction.scale_cbf_sum': Parameter containing:
tensor(5.6123), 'int_blocks.0.edge_atom_interaction.scale_rbf': Parameter containing:
tensor(9.0417), 'int_blocks.0.edge_atom_interaction.scale_cbf_sum': Parameter containing:
tensor(0.5292), 'int_blocks.0.atom_interaction.scale_rbf_sum': Parameter containing:
tensor(0.5019), 'int_blocks.0.atom_update.scale_sum': Parameter containing:
tensor(0.7639), 'int_blocks.1.trip_interaction.scale_rbf': Parameter containing:
tensor(

In [24]:
import numpy as np

# 加载 .npz 文件
data = np.load('/home/liud/Documents/code/ocp/results/is2re/all_evalai/submission_file.npz')

# 查看有哪些键（相当于字典的 key）
print("Keys in the .npz file:", data.files)

# 逐个读取数据
for key in data.files:
    print(f"{key}: shape = {data[key].shape}, dtype = {data[key].dtype}")
    # 如果想看具体值，可以打印前几项
    print(data[key][:5])  # 只打印前 5 个，避免太大

Keys in the .npz file: ['id_ids', 'id_energy', 'ood_ads_ids', 'ood_ads_energy', 'ood_cat_ids', 'ood_cat_energy', 'ood_both_ids', 'ood_both_energy']
id_ids: shape = (24948,), dtype = <U7
['252' '1133' '1208' '1417' '1510']
id_energy: shape = (24948,), dtype = float32
[-1.0234079  -1.9738832  -5.06927    -0.19715816 -1.3045686 ]
ood_ads_ids: shape = (24930,), dtype = <U7
['484' '4591' '5691' '5857' '6167']
ood_ads_energy: shape = (24930,), dtype = float32
[-4.0248404  -2.3123052   0.5974349   0.53319854  0.6967316 ]
ood_cat_ids: shape = (24965,), dtype = <U7
['993' '2026' '2362' '3498' '4762']
ood_cat_energy: shape = (24965,), dtype = float32
[-2.4762337   0.27786833  0.03296276  0.3324662  -0.89956474]
ood_both_ids: shape = (24985,), dtype = <U7
['1485' '2842' '5804' '7455' '12704']
ood_both_energy: shape = (24985,), dtype = float32
[ 0.14635512 -0.6726208  -3.2316308   0.34344596 -2.6953106 ]


In [9]:
import numpy as np

# 加载 npz 文件
data = np.load('/home/liud/Documents/code/ocp/results/is2re/all_evalai/test_ood_both/is2re_predictions_0.npz')

# 提取 'ids' 数组（假设 ids 是数字字符串）
ids = data['ids']

# 将 'ids' 转换为整数进行排序
sorted_indices = np.argsort(ids.astype(int))  # 获取排序后的索引

# 根据排序后的索引重新排列其他数据
# 例如，假设你有一个名为 'features' 的数组需要按 'ids' 排序
energy = data['energy'][sorted_indices]


# 打印排序后的数据（可选）
print("Sorted ids:", ids[sorted_indices][0:10])
print("Sorted features:", energy[0:10])

# 如果需要保存排序后的数据
np.savez('/home/liud/Documents/code/ocp/results/is2re/all_evalai/test_ood_both/is2re_predictions.npz', ids=ids[sorted_indices], energy=energy)

Sorted ids: ['1485' '2842' '5804' '7455' '12704' '14671' '21992' '23015' '35680'
 '42826']
Sorted features: [ 0.14635512 -0.6726208  -3.2316308   0.34344596 -2.6953106  -3.1612942
 -2.4497426  -2.8742888  -3.2049856  -1.6749876 ]


In [23]:
import lmdb
import numpy as np
import pickle

# 读取 LMDB 文件
def read_lmdb_sids(lmdb_file):
    env = lmdb.open(lmdb_file, readonly=True)
    with env.begin() as txn:
        cursor = txn.cursor()
        sids = []
        for key, value in cursor:
            # 假设每个数据项是一个字典，且包含 'sid' 属性
            data = pickle.loads(value)  # 示例，根据具体数据类型调整
            sid = data.sid  # 假设数据是一个包含sid的字典
            if sid is not None:
                sids.append(sid)
        return sids

# 读取 npz 文件中的 ids 属性
def read_npz_ids(npz_file):
    data = np.load(npz_file)
    return data['ids']

# 比较 LMDB 中的 sid 和 npz 中的 ids 是否一致
def compare_sids_with_ids(lmdb_file, npz_file):
    lmdb_sids = np.array(read_lmdb_sids(lmdb_file), dtype=np.int32)
    npz_ids = np.array(read_npz_ids(npz_file), dtype=np.int32)
    
    # 比较这两个列表
    if sorted(lmdb_sids) == sorted(npz_ids):
        print("LMDB 和 NPZ 文件中的 ids 一致")
    else:
        print("LMDB 和 NPZ 文件中的 ids 不一致")

# 示例调用
lmdb_file = '/media/liud/lnz_2t/OC20/is2re/all/tags12/origin/test_ood_both'
npz_file = '/home/liud/Documents/code/ocp/results/is2re/all_evalai/test_ood_both/is2re_predictions.npz'
compare_sids_with_ids(lmdb_file, npz_file)

LMDB 和 NPZ 文件中的 ids 一致


In [26]:
# checkpoint scale_dict保存为pt文件
import torch

# 加载已有 checkpoint
checkpoint = torch.load("/media/liud/lnz_2t/all_128b", map_location="cpu")
# print(checkpoint)
scale_dict = {}
for k, v in checkpoint['state_dict'].items():
    if 'scale_factor' in k:
        key = k.replace('module.', '')  # 去除 'module.' 前缀
        key = key.rsplit('.scale_factor', 1)[0]
        scale_dict[key] = torch.nn.Parameter(v.clone().detach().to(torch.float32), requires_grad=False)

torch.save(scale_dict, '/home/liud/Documents/code/ocp/configs/s2ef/all/gemnet/scaling_factors/fit_scale/gemnet_all_128b_energy.pt')
print('save')

save
